security:
    providers:
        user:
            entity:
                class: App\Entity\User
                property: email
        admin:
            entity:
                class: App\Entity\Admin
                property: email
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 15
        App\Entity\Admin:
            algorithm: auto
            cost: 15

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|img|js)/
            security: false

        user:
            pattern: ^(/$|/user|/page|/home/|/home$)
            provider: user
            anonymous: ~
            logout:
                invalidate_session: true
                path: /user/logout
                target: /
            switch_user: true
            guard:
                authenticators:
                    - App\Security\Guard\UserLoginAuthenticator

    access_control:
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, roles: [ROLE_USER, ROLE_SUPER_ADMIN] }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
